# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
